rogerclarkmelbourne/Arduino_STM32

STM32F1XX/libraries/SPI/src/SPI.cpp
tools/macosx/maple_upload

Hi Roger,
Here are a couple of patches - the first is a build fix for the SPI code on Microduino. I've checked it builds for Microduino and the Maple platforms, and that SPI.begin() runs without aborting, but I've not verified it with an actual SPI device.
The second fix is a tweak to the maple_upload script to allow dfu_util in either /opt/local/bin or /usr/local/bin.
Thanks,
Ian

SPI build fixes

---

STM32F1/libraries/SPI/src/SPI.cpp
STM32F1/libraries/SPI/src/SPI.h

Adds 5 new functions: DMA Transfer, DMA 8bit send, DMA 16bit send, write
16 bit int. and mode change to change between 8bit and 16 bit transfer.
On the existing ones I did small changes to correct some problems when receiving data, then added the 16bit ones that can send a single byte, a DMA buffer, and send a word in DMA not incrementing memory (to fill a device such as a display).
There is an extra function that changes the peripheral between 8 and 16 mode. Can be run on the fly, does not require to setup the SPI port again. You change the mode, do a 16 bit send, change the mode again, do an 8 bit send. It helps a lot with displays that use 16bit for colors, as it goes from 2 SPI transactions to only 1.

SPI DMA functions.

---

STM32F4/cores/maple/libmaple/HardwareSerial.cpp
STM32F4/libraries/arduino_uip/utility/Enc28J60Network.cpp

Hi Roger,
Another small fix for a bug found in ad-hoc testing on my STM32F4Stamp.

fix HardwareSerial::begin by doing gpio_set_af_mode AF8 when devices are UART4 or UART5

---

STM32F4/cores/maple/wirish.h

Needs include of stdlib.h for a compile to take place on the F4 variant.

Added an include of stdlib.h

---

STM32F4/libraries/arduino_uip/UIPEthernet.cpp

fix bug about DhcpClass instantiation to save 40K by avoiding link with GCC 'new' memory allocation code

fix bug about DhcpClass instantiation to save 40K by avoiding link with GCC 'new' memory allocation code

---

STM32F1/boards.txt

This changes the order of variants in the menu.
The reasoning is that the IDE selects these by default when switching board types. Code built for a smaller variant is most likely to run on one with more memory, but not the other way around.

reorder variants so smallest mem size is first

---

STM32F1/boards.txt
STM32F1/variants/nucleo_f103rb/wirish/boards.cpp
STM32F1/variants/nucleo_f103rb/wirish/boards_setup.cpp

This has now been set up as two variants on the same Nucleo F103 menu entry.
The default, i.e. first variant is the official crystall-less version @ 64 MHz.
The other one is what was already in the project - i.e. kept at 72 MHz and supporting USB.
Supersedes PR #126.

support Nucleo without and with crystal

---

tools/src/stm32flash_serial/src/serial_posix.c

This change to the stm32flash utility is needed to be able to open CDC-ACM type serial USB devices on at least Mac OSX (maybe also Linux).
It removes a check that the cflag value ends up precisely as expected by stm32flash. I don't think this is important in this context.
One more step will be needed to fully address this PR: it needs re-built versions of stm32flash for at Lac OSX and Linux (Windows code is not affected by this change).
Replaces incorrect PR #139.

Relax stm32flash checks (again)

---

STM32F1/cores/maple/HardwareSerial.cpp
STM32F1/cores/maple/HardwareSerial.h
STM32F1/cores/maple/libmaple/usart_f1.c

When the parity control is enabled, the computed parity is inserted at the MSB position (9th bit if M=1; 8th bit if M=0) and parity is checked on the received data. This excludes 9 bit long words + parity bit in the 10th position.

corrected defines needed when parity is used in HardwareSerial

---

tools/linux/49-stlinkv1.rules
tools/linux/49-stlinkv2-1.rules
tools/linux/49-stlinkv2.rules
tools/linux/install.sh

As the title says, install udev-rules for being able to use ST-link to upload sketches without having to be root.

Install udev-rules for ST-link

---

tools/src/stm32flash_serial/src/serial_posix.c

The INPCK bit is an i_flag bit, not a c_flag bit as originally done
here. I have no idea what setting INPCK in c_flag does on Linux, but
on FreeBSD it caused the test of the c_values after they were set to
fail. This fixes that, and presumably the serial interface will now
actually check the parity of incoming data.

Fix file open to actually turn on inbound parity checking.

---

STM32F1/libraries/Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.cpp

readcommand8() toggles _sclk, but when using hwSPI it's set to 0, ie. readcommand8() ends up toggling GPIO0, which it obviously shouldn't be doing. Also, when SPI-transactions had been enabled the SPI-bus speed was set to only 8MHz -- now we set it to 36MHz on STM32F1.

Bugfix Adafruit_ILI9341_STM

---

STM32F4/cores/maple/boards.cpp

Credit to hathach for finding and fixing this:
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/178
Fixes #178

fix for: PWM on STM32F4 doesn't work right away

---

STM32F1/libraries/Wire/Wire.cpp
STM32F1/libraries/Wire/Wire.h

Wire uses wrong SDA/SCL definitions

---

STM32F1/cores/maple/Print.cpp

Print::write(const void *buffer, uint32 size) always returns 0, which is against specification. This patch fixes it.

Fix return value for Print::write(const void *buffer, uint32 size)

---

STM32F1/cores/maple/libmaple/usb/stm32f1/usb_cdcacm.c
STM32F1/cores/maple/libmaple/usb/usb_lib/usb_core.c
STM32F1/system/libmaple/usb/usb_lib/usb_core.h

Various fixes for the USB core on the STM32F103. 
1. Fixed issue caused by commit [637174e63a277d3b3daa280adaa44c85bc2a5c07](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/637174e63a277d3b3daa280adaa44c85bc2a5c07) that caused issues with sending large amounts of data to the microcontroller. FIX: Revert back 2 lines of code. 
2. Added endian fix that was added to the bootloader core, but was never added to the Arduino Core. [Link here](https://github.com/leaflabs/maple-bootloader/commit/b7c8ce89331653c6d92fd7a52a43f444c8bcb739)
Discussion of these fixes can be found on the [stm32duino.com form](http://stm32duino.com/viewtopic.php?f=9&t=1451).

USB core and CDC fixes

---

STM32F1/variants/generic_stm32f103t/wirish/boards.cpp

Method adc_default_config still had the adc_dev* 'const' for F103T, but this doesn't compile.
For other boards, the 'const' was removed already.  See for example commits 0b34af3b6a29c2ea40a0005fde57f67f75829378 and
2cdbbc83390b27570c9040fc92bda6e63947f160.
Tested on Arduino IDE 1.6.13.
Compilation error message was along these lines:
STM32F1\variants\generic_stm32f103t\wirish\boards.cpp:183:34: error: invalid conversion from 'const adc_dev*' to 'adc_dev*' [-fpermissive]
STM32F1\system/libmaple/include/libmaple/adc.h:306:13: error:   initializing argument 1 of 'void adc_enable_single_swstart(adc_dev*)' [-fpermissive]
STM32F1\variants\generic_stm32f103t\wirish\boards.cpp:184:53: error: invalid conversion from 'const adc_dev*' to 'adc_dev*' [-fpermissive] …

Fix F103T compilation error: remove const

---

STM32F1/libraries/EEPROM/EEPROM.cpp
STM32F1/libraries/EEPROM/EEPROM.h

Basic EEPROM.update() function. Equivalent to original Arduino function, it checks the existing value of the address and only performs a write if the value differs from the one requested. 
Closes #248

Add EEPROM.update() function

---

STM32F1/cores/maple/libmaple/gpio_f1.c

Removed unused variable (looks like a copy/paste issue)

Compiler warning fixed

---

STM32F1/cores/maple/usb_serial.cpp
STM32F1/cores/maple/usb_serial.h

This patch avoid initializing the USB serial HW of F103C twice in the bootstrapping process. It may hangup if you initialize the HW while the USB serial port is using by host.
Please refer to discussion in the topic " USB Observations" at  http://stm32duino.com/viewtopic.php?f=28&t=2107
There is another patch which will fix this problem also.
http://stm32duino.com/viewtopic.php?f=28&t=2107&start=80#p29087

Avoid initializing USB serial twice

---

STM32F1/cores/maple/stm32f1/wirish_digital_f1.cpp

Hi,
as I mentioned in the forum [http://www.stm32duino.com/viewtopic.php?f=49&t=2079](url), the pinMode() function disables timer IRQs if setting non pwm modes on pwm capable pins. 
This little fix prevents this. It disconnects the timer from the pin, but leaves all other timer configurations as they are.

Pinmode timer

---

STM32F1/system/libmaple/include/libmaple/usart.h

See discussion at https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/260
usart_putc() blocks until space is available in the ring buffer, not until the character has been transmitted.

Fix documentation for usart_putc()

---

STM32F1/libraries/SPI/src/SPI.cpp
STM32F1/libraries/SPI/src/SPI.h

This has the addition of:
dmaSendSet
dmaSendRepeat
dmaTransferSet
dmaTransferRepeat
onTransmit
onReceive
EventCallback
I have added a few variables to the class to hold the "this" pointer for each port, so they should work fine with all 3 ports (I have tested SPI1 and SPI2 simultaneously, with different callback function for each).
It should also work with setModule, since the "this" pointer is in the settings class.
Changed TABs to spaces, previously was a mix of both, and I believe the preference is for spaces. If that's not the case I will resubmit with Tabs.
Finally, the only change to any other function is in dmaSendAsync, where I changed the variable used to hold whether there is a DMA transfer going on, so if dmaSend is used with callbacks (non-blocking) and you try to send with …

Spi callbacks

---

STM32F1/boards.txt

Linux is case sensitive so it matters when it comes to files/folder names. This fixes GD32F103xx variants in boards.txt to pick the right folder at compile time.
Otherwise this happens:
```
...
#include <board/board.h>
^
compilation terminated.
exit status 1
Error compiling for board Generic GD32F103C series.
```

linux fix for gd32 variant in boards.txt

---

STM32F1/libraries/FreeRTOS900/examples/rtos_blink/rtos_blink.ino
STM32F1/libraries/FreeRTOS900/examples/rtos_display_blink/rtos_display_blink.ino

The examples had not been edited to use the FreeRTOS 9.0 version, so correcting that now.

Correcting FreeRTOS900 examples to include right version

---

STM32F4/cores/maple/new.cpp

This is to avoid libstdc++ being pulled in when new() is used.
Already included in the F1 in 2016.
Discussed on this thread:
http://www.stm32duino.com/viewtopic.php?f=39&t=2460&p=33163

Adding new.cpp as in F1 core.

---

tools/macosx/jlink_upload

This is tested using a chinese JLink clone with Arduino 1.8.3 and a unmodified Blue Pill board
Requires the JLink binaries pre-installed from https://www.segger.com/downloads/jlink/
This is identical to the linux/jlink_upload except for the path to the binary

add JLink upload support for OSX

---

STM32F1/libraries/Wire/Wire.cpp

The current implementation will not change speed if Wire.setClock is called after begin() since the flags are only applied when the port is enabled from being disabled.
Corrected that by adding 2 lines to disable the port, and then enable it again with the new settings.
Tested and confirmed the new speed is applied.

Correct issue with I2C port speed not changing after begin()

---

STM32F1/boards.txt

As discussed in http://stm32duino.com/viewtopic.php?f=41&t=2535
Changes to the Generic Boards options so the maple dfu option is the default one and Sloeber uploads correctly.

Correction to upload issue in Sloeber

---

STM32F1/libraries/STM32ADC/src/utility/util_adc.c

This was wrong and causing warnings during compilation.

Update to util_adc.c file to pass pointer correctly.

---

STM32F1/cores/maple/Print.cpp
STM32F1/cores/maple/Print.h
STM32F1/libraries/A_STM32_Examples/examples/Communication/ASCIITable/ASCIITable.ino
STM32F1/libraries/A_STM32_Examples/examples/Communication/MIDI/Midi.ino
STM32F1/libraries/A_STM32_Examples/examples/Communication/SerialCallResponse/SerialCallResponse.ino
STM32F1/libraries/A_STM32_Examples/examples/Communication/SerialPassthrough/SerialPassthrough.ino
STM32F1/libraries/A_STM32_Examples/examples/General/USB_ASCII/USB_ASCII.ino
STM32F3/cores/maple/wirish/Print.cpp
STM32F3/cores/maple/wirish/Print.h
STM32F4/cores/maple/Print.cpp
STM32F4/cores/maple/Print.h

Several sketches:
- ASCIITable.ino
- Midi.ino
- SerialCallResponse.ino
- SerialPassthrough.ino
- USB_ASCII.ino
make use of the deprecated Serial.print(value, BYTE).
This can be replaced by Serial.write() in the sketches, seems only to be used in these sketches and results in conflicts when BYTE is defined as something else e.g. in the Elm-chan FatFS library.
Please consider this pull request as a small cleanup operation.

Removed deprecated functionality from Print class for BYTE "base"

---

STM32F1/libraries/SPI/src/SPI.cpp
STM32F1/libraries/SPI/src/SPI.h
STM32F4/libraries/SPI/src/SPI.cpp
STM32F4/libraries/SPI/src/SPI.h

Add const qualifier to SPI member function arguments for write and transmit buffers.
Qualifying the write or transfer source buffer with const avoid compile errors or casting away const when calling a SPI member function with a const source buffer.

SPI add const qualifier

---

STM32F4/cores/maple/hooks.c

copied from F1 - it was missing for 4.
Needed for yield().

Create hooks.c [F4]

---

tools/linux/maple_upload

I encountered a race condition upon which, even though the udev rules were working and uploads succeed, the serial monitor can not re-establish communications.
If the serial monitor is left open when doing an upload the error shown is:
[...]
Copying data from PC to DFU device
Starting download: [##################################################] finished!
state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Done!
Resetting USB to switch back to runtime mode
Waiting for /dev/ttyACM0 serial...Done
processing.app.SerialException: Error opening serial port '/dev/ttyACM0'. Try consulting the documentation at http://playground.arduino.cc/Linux/All#Permission
at processing.app.Serial.<init>(Serial.java:145)
at processing.app.Serial.<init>(Serial.java:82)
at …

Solve race condition with arduino IDE monitoring serial port

---

STM32F1/libraries/FreeRTOS900/utility/FreeRTOS.h

As listed in https://www.freertos.org/a00104.html#mailing_list:
"The definition of the StaticTask_t structure is incorrect if INCLUDE_xTaskAbortDelay is set to 1, or the MPU is used. The corrected structure definition can be obtained from here."
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/include/FreeRTOS.h#l978

Correct a bug in FreeRTOS

---

STM32F1/cores/maple/HardwareTimer.h

`attachInterrupt` and `detachInterrupt` functions can attach ISRs to channel 0,
which is overflow interrupt (update interrupt in RMs).

Update HardwareTimer.h documentation

---

STM32F1/cores/maple/stm32f1/wiring_pulse_f1.cpp

I took some pointers from AVR Arduino pulseInLong() and merged with the current STM32 code:
```
unsigned long pulseInLong(uint8_t pin, uint8_t state, unsigned long timeout)
{
// cache the port and bit of the pin in order to speed up the
// pulse width measuring loop and achieve finer resolution.  calling
// digitalRead() instead yields much coarser resolution.
uint8_t bit = digitalPinToBitMask(pin);
uint8_t port = digitalPinToPort(pin);
uint8_t stateMask = (state ? bit : 0);
unsigned long startMicros = micros();
// wait for any previous pulse to end
while ((*portInputRegister(port) & bit) == stateMask) {
if (micros() - startMicros > timeout)
return 0;
}
// wait for the pulse to start
while ((*portInputRegister(port) & bit) != stateMask) {
if (micros() - startMicros > timeout)
return 0;
} …
```

Complete pulseIn() using existing time measure tech

---

STM32F1/variants/generic_stm32f103v/ld/stm32f103vc.ld

regarding: --> https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/420
NOT tested !
the MCU STM32F103VC has 48kByte SRAM (see Datasheet "2.1 Device overview")
and therefore I think this *.ld file has to be corrected.
e.g. called from here - https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/boards.txt#L666

corrected RAM-length = 48kByte for STM32F103VC

---

STM32F1/variants/generic_stm32f103v/wirish/boards.cpp

tested on STM32F103VE only but surely can be used on other STM32F103xC, STM32F103xD, STM32F103xE with the same clock PLL structure.
Therefore it could be used in other "../variant/.." -folders as well, if needed.
No change to core-files needed.

option '#define XTAL16M' for boards with 16MHz-crystal

---

STM32F1/libraries/SPI/src/SPI.cpp

see https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/471

F1 SPI slave: remove RXONLY flag to enable data transmission

---

STM32F1/libraries/RTClock/src/RTClock.h
STM32F4/libraries/RTClock/src/RTClock.h

It is my first post here so let me first thank you for the library. I like it very much and it helps me with fast development of STM32 apps.
**Now the issue:**
The now() function was defined in RTClock.h using the #define directive. That is
wrong as it prevents using the keyword "now" in other situations.
The minimal error case is:
```
int now;
#include "RTClock.h"
void setup() {
now = 1;
}
void loop() {}
```
Crashes with:
```
In file included from D:\sketch_feb03a\sketch_feb03a.ino:3:0:
D:\sketch_feb03a\sketch_feb03a.ino: In function 'void setup()':
D:\arduino-1.8.5\hardware\Arduino_STM32\STM32F1\libraries\RTClock\src/RTClock.h:55:25: error: 'getTime' was not declared in this scope
#define now getTime
^
D:\sketch_feb03a\sketch_feb03a.ino:6:3: note: in expansion of macro 'now'
now = 1;
^ …
```

Fixing now() function in RTClock.h

---

STM32F1/libraries/Serasidis_XPT2046_touch/src/XPT2046_touch.cpp
STM32F1/libraries/Serasidis_XPT2046_touch/src/XPT2046_touch.h

- Add TS_Point-class and getter for better compatibility with various other touchscreen libraries out there
- Add oversampling for better accuracy. Default is seven samples per point
- Use SPI.beginTransaction() / endTransaction() to set proper SPI speed (as supported by XPT2046)

Some updates to the XPT2046 touchscreen library:

---

STM32F1/system/libmaple/stm32f1/include/series/stm32.h

The FSMC is only available in high density and XL density devices with more than 4 ports.
Basically excluded in the RC/D/E/F/G models, since they dont have enough pins.
Page 11 in the Datasheet references this. The table shows what is present, and shows the FSMC is NOT present in Rx MCUs:
http://www.st.com/content/ccc/resource/technical/document/datasheet/59/f6/fa/84/20/4e/4c/59/CD00191185.pdf/files/CD00191185.pdf/jcr:content/translations/en.CD00191185.pdf
Recent changes to other files highlight this issue during compilation time. The issue was already there, but GPIO E and GPIO F were declared and defined, while they don't actually exist in Rx MCUs, so FSMC was being included for those MCU even though they don't actually have an FSMC device, or at least no external ports to use it. 
With …

Update to fix FSMC inclusion in Rx devices

---

STM32F1/libraries/Adafruit_GFX_AS/Adafruit_GFX_AS.cpp
STM32F1/libraries/Adafruit_GFX_AS/Adafruit_GFX_AS.h
STM32F1/libraries/Adafruit_GFX_AS/README.txt
STM32F1/libraries/Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.cpp
STM32F1/libraries/Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.h

The point of this is to make drivers based on Adafruit_GFX_AS compatible with Adafruit_GFX,
without breaking existing code written for Adafruit_GFX_AS.
See also http://stm32duino.com/viewtopic.php?f=9&t=3352

Base Adafruit_GFX_AS on Adafruit_GFX, keeping only the additions in a derived class.

---

STM32F1/libraries/Wire/Wire.cpp

bugfix hw I2C unrecognized addresses 0x76, 0x77.
As discussed in http://www.stm32duino.com/viewtopic.php?f=14&t=3259&p=44458#p44392.
Tested with i2c scanner sketch.

F1 : Update Wire.cpp

---

STM32F1/libraries/Wire/utility/WireBase.cpp

Overloaded method was not returning the result.

Fixed missing return value.

---

STM32F1/variants/maple_ret6/board/board.h

It was missing, but needed since that variant (RET6) includes the SDIO peripheral, so the files are included in the compilation.

Add SDIO pin definitions to the Maple RET6 variant

---

STM32F1/variants/generic_gd32f103c/wirish/boards.cpp
STM32F1/variants/generic_gd32f103c/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103c/wirish/boards.cpp
STM32F1/variants/generic_stm32f103c/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103r/wirish/boards.cpp
STM32F1/variants/generic_stm32f103r/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103r8/wirish/boards.cpp
STM32F1/variants/generic_stm32f103r8/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103t/wirish/boards.cpp
STM32F1/variants/generic_stm32f103t/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103v/wirish/boards.cpp
STM32F1/variants/generic_stm32f103v/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103vb/wirish/boards.cpp
STM32F1/variants/generic_stm32f103vb/wirish/boards_setup.cpp
STM32F1/variants/generic_stm32f103z/wirish/boards.cpp
STM32F1/variants/generic_stm32f103z/wirish/boards_setup.cpp

This change is done for generic variants only. By default, HSE clocking scheme is used, as before this change.
Signed-off-by: Alexandr Zarubkin <me21@yandex.ru>

Added preprocessor symbol USE_HSI_CLOCK for running with HSI clocking

---

STM32F4/cores/maple/libmaple/bkp.h

Fix for the Backup RAM.
Example code:
...
#include <libmaple/bkp.h>
...
bkp_init();
bkp_enable_writes();
bkp_write(1, 0x1234); //Writes the value 0x1234 at Backup RAM address 1
bkp_disable_writes();
Serial.print(bkp_read(1)); //Print the value of the Backup RAM address 1
...

STM32F407 BKPSRAM Boundary address fix

---

STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_desc.c

Limit the maximum string length to 32 chars.
To be applied together with #549.

F4: USBD_StrDesc[] size fix (continued)

---

STM32F4/cores/maple/libmaple/usbF4/VCP/usbd_conf.h

- bug: memory overflow for size values greater than 50, in function USBD_GetString(). Value 50 allows a max string length of 24 chars.
The array in question (USBD_StrDesc) is followed in memory by 2 fill bytes for the current compile order.
Arduino 1.8.6 compiles the files in different order, so that the USB will not work anymore.
The longest string is actually 32 bytes long (plus ending zero), this will be multiplied by 2, and 2 more bytes will be added at the beginning (https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F4/cores/maple/libmaple/usbF4/STM32_USB_Device_Library/Core/src/usbd_req.c#L818-L834).
The last 2 bytes now are fill bytes (for align 4).

F4: USBD_StrDesc[] size fix

---

STM32F1/cores/maple/avr/pgmspace.h

Ran into missing pgm_read_ptr while trying to compile NeoGPS for a blue pill. This is easily fixed by adding it to the existing pgmspace.h compatibility header. Also added pgm_read_ptr_far for consistency / completeness.
This change seems to be all that is needed to make NeoGPS work on STM32F1.

Add pgm_read_ptr and pgm_read_ptr_far for better compatibility with libs written for AVR

---

STM32F4/boards.txt

Broken since: 58e50e7fd9062e45ec23d575a16cd411522c37cb
Fix #544

[STM32F4] Add missing build.vect_flags for netduino2plus

---

STM32F1/libraries/SPI/src/SPI.cpp
STM32F1/libraries/SPI/src/SPI.h
STM32F4/libraries/SPI/src/SPI.cpp

_settings[] array is accessed beyond the end of the array if BOARD_NR_SPI is defined as 1 on for example the HyTiny board.
Running NodeManager/MySensors software crashes with a SIGSEGV due to SPI issue where _settings[] array is written to beyond the end of the array and places the address of dma1() in the getTimePtr in the Arduino Time.cpp library.  This occurs when _settings[1].spiRxDmaChannel is assigned DMA_CH4 in SPI.cpp on the HyTiny where the _settings[] array is only one element long.

Protect _settings[] array from accesses beyond end

---

tools/linux/stlink_upload
tools/linux64/stlink_upload
tools/macosx/stlink_upload

The number of arguments being passed to the stlink_upload script on
linux, linux64, macosx is one (this may have been more in the past but
the with version 1.8.8) this is now only a single argument.
The change changes the variable referenced in the script from $4 to $1.
This change already appears to have been applied to the windows version
of the script.
This appears to be open issue also #604

Fixed incorrect arguments for stlink_upload

---

STM32F1/libraries/RTClock/examples/RTCAdj/RTCAdjust.ino
STM32F1/libraries/RTClock/examples/RTCAdj/readme.md
STM32F1/libraries/RTClock/examples/RTCAdj/rtadjust.cpp
STM32F1/libraries/RTClock/examples/RTCAdj/rtadjust.h

this PR replaces the old PR
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/581
this commit provides examples to adjust for RTC drifts
as discussed in thread
http://www.stm32duino.com/viewtopic.php?f=18&t=4365
it provides a new set of source files in
STM32F1/libraries/RTClock/examples/RTCAdj
these examples uses RTClock functionality
and do not affect/or change existing functionality

RTC Adjustment examples

---

STM32F1/system/libmaple/timer_private.h

To clear specific bits in TIMx_SR registers, libmaple uses
```
TIMx_SR &= ~(events_handled);  // wrong
```
This is wrong. The `&=` operator expands to a read-modify-write sequence consisting of multiple instructions. If a new event occurs between the read from TIMx_SR and the write to TIMx_SR, that new event will be cleared immediately without ever being noticed or handled.
A better way to clear specific bits is
```
TIMx_SR = ~(events_handled);  // good
```
This writes '0' to the bits to be cleared, and '1' to all other bits. The hardware will not allow software to change any SR bits from 0 to 1; only hardware events can do that. So bits written as '1' are effectively ignored and bits written as '0' are cleared. Exactly what we need.
I tested this in my program which captures input on …

Fix clearing of TIMx_SR register

---

STM32F1/libraries/STM32ADC/src/utility/util_adc.c

Fix a compiler warning that an `extern` cannot be set in its declaration.

Remove errant "init" of extern

---

STM32F1/libraries/STM32ADC/src/utility/util_adc.h

when I tried to use STM32ADC::setChannels method I got an error about missing function implementation from util_adc.c file, which was caused by missing extern "C" declaration in util_adc.h file.

Added missing extern C to STM32ADC helper files

---

STM32F1/cores/maple/libmaple/usb/usb_lib/usb_mem.c

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/a3a56866505eeca4b49fc435700dcd4bd5540c8c/STM32F1/system/libmaple/include/libmaple/usb_cdcacm.h#L155
This structure takes up 7 bytes of RAM, under some memory-aligned compilation rules, it takes up 8bytes
This structural variable is passed into the 
`PMAToUserBufferCopy` function as a
` u8 * pbUsrBuf `parameter in here https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/a3a56866505eeca4b49fc435700dcd4bd5540c8c/STM32F1/cores/maple/libmaple/usb/usb_lib/usb_mem.c#L60
If the length of the `pbUsrBuf` parameter is odd, it will tamper with the last byte of the address.
If the compiler is single-byte aligned, the structure `line_coding` takes up 7bytes, At this point, the value of the variable that follows `line_coding` will be …

[bugfix] Restore overflowed memory copy

---

STM32F1/libraries/SPI/src/SPI.cpp
STM32F1/libraries/SPI/src/SPI.h

- use const for ff variable to avoid unused variable on each SPI.h include
- move the spi_this refs where its used...
- and also the 3 others ones :
STM32F1\libraries\SPI\src\SPI.cpp:784:12
warning: enumeration value 'RCC_AHB' not handled in switch [-Wswitch]
STM32F1\libraries\SPI\src\SPI.cpp:392:5:
warning: this 'while' clause does not guard... [-Wmisleading-indentation]
Sample use : https://travis-ci.org/MarlinFirmware/Marlin/jobs/564740480

SPI: fix annoying unused variables warnings

---

STM32F1/system/libmaple/usart_private.h

Currently HardwareSerial uart does not check if a framing error
(parity error or invalid stop bit) has occured and simply
forward the received byte to the caller. This results in spurious
invalid data being received e.g. when the uart pin is left floating
or when a connected device is reset. This confuses apps using uart,
and cause apps to abort with errors.
this fix checks received bytes for framing error (parity error or
stop bit errors) and discards them if a framing error occured

bugfix:HardwareSerial check framing or parity error

---

STM32F1/libraries/A_STM32_Examples/examples/Sensors/HardTimerAsEncoder/HardTimerAsEncoder.ino

I've tested this fix on a maple mini with 'compiler.warning_flags.all' selected.
The example is located here: Arduino_STM32/examples/Sensors/HardTimerAsEncoder/HardTimerAsEncoder.ino

The HardTimerAsEncoder.ino example got stuck on an ASSERT_FAULT.

---

STM32F1/variants/generic_stm32f103c/wirish/start_c.c

main() never exits. The subsequent call to exit() (which can never be reached) links in the libc exit symbol and all that it calls (including free(), exitproc and a few others).
Removing this saves around 2k of flash in most cases.

Remove uncallable libc call

---

STM32F1/platform.txt

C++ requires that static object destructors are called when the
program terminates. Recent versions of GCC use __cxa_atexit to
register exit handlers which call these object destructors.
With the -fno-use-cxa-atexit command line option, GCC uses atexit
instead (same functionality, but only up to 32 exit handlers can
be registered).
Since the Arduino main process can not return, and calls to exit()
simply call an infinite loop - this is completely irrelevant. No exit 
handlers are ever called.
By removing the unused __cxa_atexit functionality we save a bit of
space, and enable further cleanups (in later commits).

Add -fno-use-cxa-atexit compiler option to reduce unused code.

---

STM32F1/cores/maple/ext_interrupts.h
STM32F1/cores/maple/libmaple/exti.c
STM32F1/system/libmaple/dma_private.h
STM32F1/system/libmaple/include/libmaple/libmaple_types.h
STM32F1/system/libmaple/include/libmaple/nvic.h
STM32F1/system/libmaple/include/libmaple/usb_cdcacm.h
STM32F1/system/libmaple/stm32f1/include/series/gpio.h
STM32F1/system/libmaple/stm32f1/include/series/spi.h
STM32F1/system/libmaple/stm32f2/include/series/dma.h
STM32F1/system/libmaple/timer_private.h
STM32F1/system/libmaple/usart_private.h

replaces "static __always_inline" with "inline" directive

fix: remove warning __always_inline not always possible

---

STM32F1/cores/maple/libmaple/usb/stm32f1/usb_reg_map.c
STM32F1/system/libmaple/include/libmaple/usb.h

A couple of libmaple additions to prepare for usb composite audio device class. Allows double buffered isochronous IN endpoints to function correctly. Fixes #687.

Prepare for audio device class

---

STM32F1/cores/maple/libmaple/i2c.c

This fixes #704 
The I2C master mode 2-byte read was incorrectly NAKing prematurely causing the second byte of all 2-byte reads to be returned as `FF`.
As per the ST datasheet for the CR1 register when using read Method 2, it's very important to clear the ACK bit AFTER clearing the ADDR (not before the ADDR is cleared!):
>Note: The POS bit is used when the procedure for reception of 2 bytes (see Method 2:
transfer sequence diagram for master receiver when N=2) is followed. It must be
configured before data reception starts. In this case, to NACK the 2nd byte, the ACK bit
must be cleared just after ADDR is cleared. To check the 2nd byte as PEC, the PEC bit
must be set during the ADDR stretch event after configuring the POS bit.
This PR swaps the clearing of the ACK-bit to after clearing …

Fix I2C master 2-byte read case

---

STM32F1/cores/maple/libmaple/i2c.c

Disable only I2C IRQs when avoiding IRQ race-condition instead of global interrupts.  This avoids affecting the entire system timing when waiting for I2C state change.

Keep I2C IRQ processing from affecting system timing

---

STM32F1/cores/maple/libmaple/i2c.c

This is the PR that fixes #638 and is equivalent to the bundle I posted there at [fix_i2cmaster_StopOnNACK.zip](https://github.com/rogerclarkmelbourne/Arduino_STM32/files/3907857/fix_i2cmaster_StopOnNACK.zip)
The NACK should only be sent by the master and the only one missing was the error case in the this interrupt handler for the AF (acknowledge failed) case.  The other stop conditions are handled by the main interrupt routine.
Adding a stop to all paths would be wrong because it can actually cause a restart condition with the I2C if the previous one had finished.

I2C Master should send a STOP when receiving NACK error (SR1_AF)

---

STM32F1/boards.txt
STM32F1/variants/generic_stm32f103c/ld/jtag_k6.ld

This PR adds support for the 32K flash/10K ram blue pill boards:
https://embeddedtronicsblog.wordpress.com/2018/12/29/fake-stm32-blue-pill-boards/
The current bootloader doesn't work with these, but serial upload works fine.

support for fake stm32f103c8t6

---

STM32F1/cores/maple/cxxabi-compat.cpp

Fix for issue #688
This fix help me reduce Marlin firmware size from 134040 to 103700 bytes (~23%).
So it can fit in 128KB flash.

Avoid C++ demangle to reduce binary size

---

STM32F1/libraries/USBComposite/USBMIDI.h
STM32F1/libraries/USBComposite/USBMassStorage.h
STM32F1/libraries/USBComposite/USBXBox360.h

*USBComposite.h* includes *USBMIDI.h*, *USBMassStorage.h* and *USBXBox360.h*
which include *USBComposite.h*.
Include guard in *USBComposite.h* prevents compile errors, but it
causes Qt Creator's clang code model to show errors and stop working.

USBComposite: fix circular dependency

---

STM32F1/platform.txt

The `ARDUINO_ARCH_{build.arch}` is used to differentiate core.
See: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#working-with-multiple-architectures
Defining  `ARDUINO_ARCH_STM32` will raised several issues on library supporting both cores:
* `ARDUINO_ARCH_STM32`
* `ARDUINO_ARCH_STM32F1`
This was introduced here:
https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/2208bcbc5bcff8c25feb3713cdb72f546366957c

ARDUINO_ARCH_STM32 should not be defined

---

STM32F1/cores/maple/libmaple/rcc.c
STM32F1/cores/maple/libmaple/usb/stm32f1/usb_cdcacm.c
STM32F1/libraries/OLED_I2C/OLED_I2C.cpp
STM32F1/variants/STM32VLD/wirish/syscalls.c
STM32F1/variants/generic_gd32f103c/wirish/syscalls.c
STM32F1/variants/generic_stm32f103c/wirish/syscalls.c
STM32F1/variants/generic_stm32f103r8/wirish/syscalls.c
STM32F1/variants/generic_stm32f103t/wirish/syscalls.c
STM32F1/variants/generic_stm32f103v/wirish/syscalls.c
STM32F1/variants/generic_stm32f103z/wirish/syscalls.c
STM32F1/variants/hytiny_stm32f103t/wirish/syscalls.c
STM32F1/variants/maple/wirish/syscalls.c
STM32F1/variants/maple_mini/wirish/syscalls.c
STM32F1/variants/maple_ret6/wirish/syscalls.c
STM32F1/variants/microduino/wirish/syscalls.c
STM32F1/variants/nucleo_f103rb/wirish/syscalls.c
STM32F3/cores/maple/libmaple/rcc.c

Same as #274 but only fixing -Wsign-compare.
Most of these fixes are self explanatory.
The question is if `rcc_sysclk_src<<2` should be type-casted to `uint32` or `unsigned int`, as I did.
```
typedef enum rcc_sysclk_src {
RCC_CLKSRC_HSI = 0x0,
RCC_CLKSRC_HSE = 0x1,
RCC_CLKSRC_PLL = 0x2,
} rcc_sysclk_src;
```

Fixed 'warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

---

STM32F4/cores/maple/wirish.h

Hi,
digitalPinToInterrupt macro seems to be missing for STM32F4, which causes an issue if some Arduino library happens to be using it ;)
I added it the same way it was done on STM32F1.

Added digitalPinToInterrupt macro for STM32F4

---

STM32F1/cores/maple/wirish_math.h
STM32F4/cores/maple/wirish_math.h

Fixing issue https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/788

Prevent min and max macro definitions from colliding with the stdlib ones.

---

STM32F1/cores/maple/tone.cpp

stm32f103 timer only 4 channels, so the default `#define TONE_CHANNEL 8` is invalid

bugfix tone.cpp, stm3f103 timer only 4 channels

---

STM32F1/libraries/Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.cpp
STM32F1/libraries/Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.h

After switching from an older version of this library, I noticed some drawing code was running a lot more slowly. After some testing, I narrowed it down to the behaviour of DMA_ON_LIMIT. It seems like, in at least some cases, the current setting can result in a big slowdown: in my tests on an STM32F103C8T6 'blue pill' board, I got the following results:
- With DMA_ON_LIMIT as is, calls to drawFastVLine took an average of 260 microseconds.
- With the conditionals on DMA_ON_LIMIT commented out (so that it would always use DMA), calls to drawFastVLine took an average of 160 microseconds.
This adds up: when you're trying to call the function 2000+ times per second (e.g., to draw out a waveform on screen in something approaching realtime), it makes a big difference.
**This pull request makes …

Adafruit_ILI9341_STM (stm32f1): Allow user to force the use of DMA.

---

STM32F4/cores/maple/libmaple/adc.c
STM32F4/cores/maple/libmaple/adc.h
STM32F4/libraries/STM32F4_ADC/examples/PR784F4AdcTest/PR784F4AdcTest.ino
STM32F4/libraries/STM32F4_ADC/examples/PR784F4AdcTest/readme.md

- ADC1, ADC2, ADC3 fixup for invalid conversion from const errors
initially i'm running into some errors: invalid conversion from
'const adc_dev*' while using ADC1, ADC2, ADC3
```
extern const adc_dev adc1;
extern const adc_dev adc2;
extern const adc_dev adc3;
#define ADC1 (&adc1)
#define ADC2 (&adc2)
#define ADC3 (&adc3)
```
those errors are resolved by defining them as follows
```
extern const adc_dev adc1;
extern const adc_dev adc2;
extern const adc_dev adc3;
#define ADC1 ((adc_dev*) &adc1)
#define ADC2 ((adc_dev*) &adc2)
#define ADC3 ((adc_dev*) &adc3)
```
- add adc_prescaler
this is modeled after the same function in the F1 core, the macro symbols are same as well. this would make it more 'compatible' for those writing codes that may possibly be used in both F1 and F4 sets.
adc.h
``` …
```

F4: updates in adc.h and adc.c

---

STM32F4/platform.txt

Two Quotation marks were missing and therefore the build fails for some users with spaces in their temp path (like me).

Fix spaces in paths for F4

---

STM32F1/platform.txt
tools/win/maple_upload.bat

This solves the problem where this batch file may use a different Java version compared to the one provided by the Arduino IDE. 
(see Issue #813)

Fix Java PATH problem on Windows (Fix Issue #813)

---

STM32F1/libraries/RTClock/examples/RTCAdjust/RTCAdjust.ino
STM32F1/libraries/RTClock/examples/RTCAdjust/readme.md
STM32F1/libraries/RTClock/examples/RTCAdjust/rtadjust.cpp
STM32F1/libraries/RTClock/examples/RTCAdjust/rtadjust.h

Incremental calibration allows the user to call calibratertc() repeatedly.
This is done by running synctime() once and the user can then call calibratertc(() more than once.
calibratertc() computes the drift adjustments by adding up the cumulative adjustments each time the user call calibratertc(). By doing this, it accounts for the smaller differential errors detected from the elapsed time since the initial synctime() call, and hopefully provide more accurate adjustments over a longer time period.
so initially call synctime() then afterwards you can call calibratertc() more than once with the new time to sync, for each time it measures the total elapsed time difference from the initial time sync to get the differential error. And add this incremental error to the drift_duration which is …

F1: RTCAdjustment example add incremental calibration

---

STM32F1/cores/maple/libmaple/usb/stm32f1/usb_cdcacm.c
STM32F1/libraries/USBComposite/usb_composite_serial.c

Fixed bug in composite_cdcacm_peek_ex.
rx_unread was calculated incorrectly in case offset>0. The too low rx_unread leads to len being set to a very high number in the next lines, causing the software to crash.

Fixed bug in composite_cdcacm_peek_ex

---

STM32F4/cores/maple/libmaple/bkp.c
STM32F4/cores/maple/libmaple/bkp.h
STM32F4/cores/maple/libmaple/rccF4.h
STM32F4/libraries/RTClock/examples/BkpTest/BkpTest.ino
STM32F4/libraries/RTClock/examples/BkpTest/readme.md
STM32F4/libraries/RTClock/src/RTClock.cpp

STM32F4: update bkp.h, bkp.c add support for backup registers and backup sram.
added example in STM32F4/libraries/RTClock/examples/BkpTest

STM32F4 backup domain registers and backup domain sram

---

STM32F1/libraries/Adafruit_GFX_AS/Adafruit_GFX_AS.cpp
STM32F1/libraries/SPI/src/SPI.h

The ILI9341 has depended on a fairly ancient (1.5.3) version of the Adafruit GFX Library. 
This commit makes it compatible with the current HEAD versions of the Adafruit GFX Library by making the following two changes:
- Update references to use textsize_x (renamed in version 1.5.4 of the graphics library) when calculating positions/sizes in Adafruit_GFX_AS.cpp.
- Provides the SPIClass::transfer(...) method expected by Adafruit BusIO's SPIDevice class.

Adafruit_ILI9341_STM (stm32f1): Compatibility with current HEAD versions of Adafruit GFX

---

STM32F1/boards.txt
STM32F1/variants/generic_stm32f103c/wirish/boards_setup.cpp

I have tested this with a generic F103C8 without a crystal and it works fine along with USB, SPI, UART etc, I don't see any issues apart from maybe the obvious clock inaccuracy of the internal RC, but other than that this feature was pretty handy for me and I feel like it should've been there already.

Added build options to select HSI clock source - Generic F103C8

---

STM32F1/libraries/EEPROM/EEPROM.cpp
STM32F1/libraries/EEPROM/EEPROM.h
STM32F1/libraries/EEPROM/examples/EEPROM_example/EEPROM_example.ino

Defines paremeter Pages for use more than one page per bank on emulated EEPROM.

Increment size of emulated EEPROM

---

STM32F4/libraries/Wire/WireBase.cpp
STM32F4/libraries/Wire/WireBase.h

Methods `write()` of the WireBase class for STM32F4 (`STM32F4/libraries/Wire/WireBase.h`) are erroneously defined as void, which makes them incompatible with recent versions of libraries such as Adafruit GFx. The same methods in the branch for STM32F1 returns int and doesn't produce incompatibility errors.
The fix adds a return value to methods, fixing compatibility issues.

Add return values to STM32F4 Wire.write() methods to be compatible with recent Adafruit libraries

---

STM32F1/libraries/SPI/src/SPI.h

Two overloaded `SPI.transfer()`methods in file `STM32F1/libraries/SPI/src/SPI.h`:
```
void transfer(const void * buffer, size_t length);
void transfer(uint8_t * trx_buf, uint32 len);
```
produces a "call is ambiguous" error if called as:
`spi.transfer(uint8*, size_t);`
Making the type of second parameter the same in both methods eliminates the error.

Fix "call to overloaded transfer() is ambiguous" issue
