STM32F1/libraries/MapleCoOS116/utility/OsTime.h
STM32F1/libraries/MapleCoOS116/utility/OsTimer.h
STM32F1/libraries/MapleCoOS116/utility/arch.c
STM32F1/libraries/MapleCoOS116/utility/coocox.h
STM32F1/libraries/MapleCoOS116/utility/core.c
STM32F1/libraries/MapleCoOS116/utility/event.c
STM32F1/libraries/MapleCoOS116/utility/flag.c
STM32F1/libraries/MapleCoOS116/utility/hook.c
STM32F1/libraries/MapleCoOS116/utility/kernelHeap.c
STM32F1/libraries/MapleCoOS116/utility/mbox.c
STM32F1/libraries/MapleCoOS116/utility/mm.c
STM32F1/libraries/MapleCoOS116/utility/mutex.c
STM32F1/libraries/MapleCoOS116/utility/port.c
STM32F1/libraries/MapleCoOS116/utility/queue.c
STM32F1/libraries/MapleCoOS116/utility/sem.c
STM32F1/libraries/MapleCoOS116/utility/serviceReq.c
STM32F1/libraries/MapleCoOS116/utility/task.c
STM32F1/libraries/MapleCoOS116/utility/task.c.original
STM32F1/libraries/MapleCoOS116/utility/time.c
STM32F1/libraries/MapleCoOS116/utility/timer.c
STM32F1/libraries/MapleCoOS116/utility/utility.c
STM32F1/libraries/MapleCoOS116/utility/utility.h

Ported FreeRTOS 8.2.1 by finding the changes in the 7.0.1 version and
carrying them over. Then found an almost working port of CoOS 1.12 (a few years old), and
corrected it to work, and then carried the changes to 1.1.6 (latest). Tested all
of them with USBSerial, GPIO, SPI, and SPI DMA (with ISR and all).
Similar examples ported to all of them.

CoOS 1.12 and 1.1.6 (latest), and FreeRTOS 8.2.1

---

README.md

This is a super easy pull-request. Not much to review. Just an improved readme.

update to readme--added a bunch of support links

---

STM32F4/variants/discovery_f407/variant.h

add missing/forgotten variant.h

add missing/forgotten variant.h

---

STM32F4/cores/maple/libmaple/HardwareSerial.cpp
STM32F4/cores/maple/libmaple/HardwareSerial.h
STM32F4/cores/maple/libmaple/ring_buffer.h
STM32F4/cores/maple/libmaple/usart.h
STM32F4/cores/maple/usb_serial.cpp
STM32F4/cores/maple/usb_serial.h

convert USBSerial and HardwareSerial to derived from Stream instead of Print

convert USBSerial and HardwareSerial to derived from Stream instead of Print

---

STM32F4/cores/maple/IPAddress.cpp
STM32F4/cores/maple/IPAddress.h

change IPAddress::toCharArray() into IPAddress::toString() 
This is more obvious according to some discussion in ESP forums, so I made the same change here.

change IPAddress::toCharArray() into IPAddress::toString()

---

STM32F4/variants/discovery_f407/discovery_f4.cpp
STM32F4/variants/discovery_f407/discovery_f4.h

Those GPIOF/GPIOG pins were missing ...

add GPIOF/GPIOG pins to allow F429 using them

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/breakouttouchpaint/breakouttouchpaint.ino
STM32F1/libraries/Touch-Screen-Library_STM/README.txt
STM32F1/libraries/Touch-Screen-Library_STM/TouchScreen_STM.cpp
STM32F1/libraries/Touch-Screen-Library_STM/TouchScreen_STM.h
STM32F1/libraries/Touch-Screen-Library_STM/examples/touchscreendemo/touchscreendemo.pde
STM32F1/libraries/Touch-Screen-Library_STM/examples/touchscreendemoshield/touchscreendemoshield.ino

Added Adafruit Resistive Touchscreen library with STM32 support. Edited Adafruit_ILI9341_STM breakouttouchpaint example to use ported library.

Added Touchscreen Library

---

tools/linux/maple_upload

Fix case of spaces in path to linux tools directory

---

STM32F4/libraries/RTClock/library.properties
STM32F4/libraries/RTClock/src/RTClock.cpp
STM32F4/libraries/RTClock/src/RTClock.h

Roger, this is the initial push for the new RTClock for STM32F4.
I will try to make interrupts handling in the following days.

initial push of RTClock for STM32F4

---

STM32F4/libraries/RTClock/src/RTClock.cpp
STM32F4/libraries/RTClock/src/RTClock.h

I've finally understood the multiple levels of write protection and the relation with the EXTI and NVIC.

make PeriodicWakeup and AlarmA/AlarmB working

---

STM32F4/cores/maple/libmaple/bkp.c
STM32F4/cores/maple/libmaple/bkp.h

I did a mess yesterday : I though doing a remove of old bkp.c.xxx and bkp.h.xxx, and adding bkp.c and bkp.h, but instead, those were symbolic links and GIT were threating then as is, and I didn't notice that.
(But that good to know if one day we need really symbolic links for common stuff)

put back original bkp.* files (not symlink)

---

STM32F1/cores/maple/IPAddress.cpp
STM32F1/cores/maple/IPAddress.h

Hi Roger,
I've done this helper several months ago in F4, but I've never commit it under F1 ...

add toString() helper to IPAddress class

---

STM32F4/boards.txt

ref: http://stm32duino.com/viewtopic.php?f=39&t=537&start=30

max flash size is incorrect for the discovery F407

---

STM32F1/cores/maple/HardwareSerial.cpp
STM32F1/cores/maple/libmaple/usart.c
STM32F1/cores/maple/libmaple/usart_f1.c
STM32F1/system/libmaple/include/libmaple/usart.h
STM32F1/system/libmaple/usart_private.h

Minimal changes to implement buffered interrupt-based TX with static buffer.

F1 usart   buffered interrupt based tx (static tx buffer)

---

STM32F1/platform.txt
STM32F3/platform.txt
STM32F4/libraries/RTClock/library.properties
STM32F4/libraries/SPI/library.properties
STM32F4/libraries/arduino_uip/library.properties
STM32F4/platform.txt

Update for recipe.ar.pattern and library 'Category not valid' IDE warnings

Update for recipe.ar.pattern and library 'Category not valid' IDE warnings

---

STM32F1/cores/maple/IPAddress.cpp
STM32F1/cores/maple/IPAddress.h
STM32F1/cores/maple/Print.cpp
STM32F1/cores/maple/Print.h
STM32F1/cores/maple/Stream.cpp
STM32F1/cores/maple/Stream.h
STM32F1/cores/maple/WString.cpp
STM32F1/cores/maple/WString.h
STM32F4/cores/maple/IPAddress.cpp
STM32F4/cores/maple/IPAddress.h
STM32F4/cores/maple/Print.cpp
STM32F4/cores/maple/Print.h
STM32F4/cores/maple/Stream.cpp
STM32F4/cores/maple/Stream.h
STM32F4/cores/maple/WString.cpp
STM32F4/cores/maple/WString.h

Solution to #215 . Merge minor API changes of IPAddress, Print, Stream and WString from official Arduino core source. LookaheadMode is still under evaluation since I haven't encounter the feature in my code and they can cause hage change to extsting code.

merge minor API changes

---

STM32F1/cores/maple/HardwareTimer.cpp
STM32F1/cores/maple/HardwareTimer.h
STM32F1/cores/maple/libmaple/adc.c
STM32F1/libraries/STM32ADC/examples/SingleChannelAtSampleRateCircularBuffer/SingleChannelAtSampleRateCircularBuffer.ino
STM32F1/libraries/STM32ADC/src/utility/util_adc.c

No sure for the compile error in util_adc.c but ADC_CR2_TSEREFE don't exists

To use STM32ADC in continuous mode triggered by an internal timer

---

README.md

Fixed headings

---

STM32F4/libraries/RTClock/examples/Test_RTClock/Test_RTClock.ino
STM32F4/libraries/RTClock/library.properties
STM32F4/libraries/RTClock/src/RTClock.cpp
STM32F4/libraries/RTClock/src/RTClock.h

- no need for extra time library.
I took code snippets from Teensy's Time lib.
- as discussed in the forum: http://www.stm32duino.com/viewtopic.php?f=39&t=775&p=31218#p31218

Reworked RTC for F4

---

STM32F3/boards.txt
STM32F3/platform.txt
STM32F4/boards.txt
STM32F4/platform.txt

Added F3/F4 menu opts for compiler - continuing from here: https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/313

Menu optimizations support for F3/F4 boards

---

STM32F4/cores/maple/boards.cpp

- remove repeated call to setup serial USB in the initial setup phase

Update boards.cpp [F4] - remove repeated call to setup serial USB

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/touchpaint/touchpaint.ino

- use Adafruit_GFX_AS lib instead of Adafruit_GFX

Update touchpaint.ino [Adafruit_ILI9341_STM]

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/spitftbitmap/spitftbitmap.ino

- use Adafruit_GFX_AS lib instead of Adafruit_GFX

Update spitftbitmap.ino [Adafruit_ILI9341_STM]

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/onoffbutton_breakout/onoffbutton_breakout.ino

- use Adafruit_GFX_AS lib instead of Adafruit_GFX

Update onoffbutton_breakout.ino [Adafruit_ILI9341_STM]

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/onoffbutton/onoffbutton.ino

use Adafruit_GFX_AS lib instead of Adafruit_GFX

Update onoffbutton.ino [Adafruit_ILI9341_STM]

---

STM32F1/libraries/Adafruit_ILI9341_STM/examples/graphicstest/graphicstest.ino

- use Adafruit_GFX_AS lib instead of Adafruit_GFX

Update graphicstest.ino [Adafruit_ILI9341_STM]

---

STM32F1/cores/maple/sdio.cpp
STM32F1/libraries/SDIO/SdioF1.cpp
STM32F1/libraries/SDIO/SdioF1.h
STM32F1/system/libmaple/include/libmaple/sdio.h
STM32F1/variants/generic_stm32f103r/board/board.h

To enable 4bit wide mode, uncomment from this line to line 496:
https://github.com/victorpv/Arduino_STM32/blob/patch-3/STM32F1/libraries/SDIO/SdioF1.cpp#L491
In line 513 in that same file you can adjust the speed. I have tested from 1Mhz (1000) up, but with my card reader doesn't seem to work fine past 1Mhz. I have checked with a logic analyzer and the frequencies look right,

F1 SDIO first version

---

STM32F4/libraries/RTClock/src/RTClock.cpp

bugfix setAlarmATime - corrected day variable

Update RTClock.cpp [F4]

---

STM32F1/variants/generic_stm32f103v/board/board.h
STM32F1/variants/generic_stm32f103z/board/board.h

Hi Roger,
Please review this simple patch!

Added missing SDIO pins for F103V and F103Z

---

STM32F1/libraries/RTClock/src/RTClock.cpp
STM32F1/libraries/RTClock/src/RTClock.h

For 1/2 or 3/4 of hour TimeZone.

Add TimeZone(UnixTime, HourOffset, MinuteOffset)

---

STM32F1/system/libmaple/include/libmaple/atomic.h

as discussed here: https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/403, taken from http://www.stm32duino.com/viewtopic.php?f=3&t=258&start=10

Create new file "atomic.h"

---

STM32F1/cores/maple/stm32f1/wirish_debug.cpp

reserve SWD lines only for debug

Update wirish_debug.cpp - reserve SWD lines only for debug

---

STM32F1/libraries/STM32ADC/src/STM32ADC.h

See https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/402

Fix compilation with -std=gnu++11

---

STM32F1/cores/maple/libmaple/usb/stm32f1/usb_cdcacm.c

Fixed 'warning: multi-line comment [-Wcomment]'

---

.gitignore

See [core_stm32](https://github.com/stm32duino/Arduino_Core_STM32/pull/192) for description

Added platform.local.txt and boards.local.txt to .gitignore

---

STM32F4/cores/maple/wirish_math.h

similar to already existing solution for F1

F4: add the macro "word"

---

STM32F1/cores/maple/tone.cpp

Small change to increase tone resolution by multiplying before dividing.

Increase tone resolution

---

STM32F1/platform.txt

cosmetics: remove unnecessary blank space
Reduces line length of build output message.

Update platform.txt - Reduces line length of build output message

---

tools/linux64/install.sh

`adduser` isn't available on all linux systems. 
`usermod` is available.

Use useradd instead of adduser

---

STM32F1/system/libmaple/include/libmaple/scb.h

Fix SCB_AIRCR_PRIGROUP

---

STM32F1/cores/maple/sdio.cpp
STM32F1/libraries/SDIO/SdioF1.cpp
STM32F1/libraries/SDIO/SdioF1.h
STM32F1/system/libmaple/include/libmaple/sdio.h

Changes __io for __IO
Increases the time for some delays
Adds compatibility with SdSdioEX class while using DMA
Implement a retry mechanism (needs further testing)
Implement command ACMD42 to disconnect the sd internal pullup in D3 in 4bit mode
Some other small changes to increased reliability in bluepillF4 with F1 mcu

Multiple updates to SDIO library

---

STM32F4/cores/maple/Print.cpp

F4: update Print.cpp

---

STM32F1/libraries/RTClock/src/RTClock.cpp
STM32F1/libraries/RTClock/src/RTClock.h

Signed-off-by: Alexandr Zarubkin <me21@yandex.ru>

Changed prescaler variable type to uint32. Fixes #520.

---

STM32F1/libraries/SPI/examples/spi_slave/spi_slave.ino

A very simple SPI slave example, I think the project lacks simple examples like this; it helps a lot getting things running!

Add simple SPI slave example

---

STM32F1/system/libmaple/stm32f1/include/series/dma.h

Utility function to check the number of transfer yet to be done by DMA.

F1: added function dma_get_count

---

STM32F1/boards.txt
STM32F1/platform.txt
STM32F4/boards.txt
STM32F4/platform.txt

Useful when using arduino-builder

Define defaults build.flags

---

STM32F1/cores/maple/HardwareSerial.cpp

I already tested it and it work fine.

fix not working availableForWrite for STM32F1

---

STM32F4/boards.txt

See http://stm32duino.com/viewtopic.php?f=32&t=3661&start=150#p49567.
Without this the HID upload won't work with Arduino IDE.

F4: fix HID upload with Arduino IDE

---

STM32F1/platform.txt
STM32F4/platform.txt

According to http://www.stm32duino.com/viewtopic.php?f=16&t=4377&p=51233#p51233

Explicit STM32duino.com platform origin

---

STM32F1/cores/maple/Stream.cpp

Fixed a float constant so double precision multiply is not linked in

Fixed float constant

---

STM32F1/cores/maple/usb_serial.cpp

Current implementation of reset to bootloader routine in `rxHook` from file `STM32F1/cores/maple/usb_serial.cpp` can cause receiving signal SIGSEGV during try to upload new sketch. The mechanism of that is described by me with details here : http://www.stm32duino.com/viewtopic.php?f=53&t=4125 and its occurence is dependant of USB data structures location in RAM.
Proof-of-concept sketch, triggering described behavior was tested on Arduino IDE 1.8.7 on Linux x64 with latest commit of Arduino_STM32 and it can be downloaded here : https://gist.github.com/shodan8192/b1b68d747f4395da3edb37e6300e39e7
First upload of this sketch will be succesfull. Next try will cause fast pulsation of LED and message : `dfu-util: No DFU capable USB device available`. After manual reset, board is in "perpetual …

Fix for possible break of DFU functionality

---

STM32F1/cores/maple/avr/pgmspace.h
STM32F4/cores/maple/avr/pgmspace.h

This function is used in some projects (Marlin) and require to be defined

Handle strchr_P alias for AVR code compat

---

STM32F1/cores/maple/libmaple/exti.c
STM32F1/cores/maple/libmaple/usart_private.c
STM32F1/system/libmaple/dma_private.h
STM32F1/system/libmaple/timer_private.h
STM32F1/system/libmaple/usart_private.h

fix unresolved inline functions with newer compiler versions

---

STM32F1/libraries/Wire/utility/WireBase.h

Added virtual end() to WireBase, like standard Arduino.

---

STM32F1/cores/maple/avr/dtostrf.c

Fix suggested by @HamidSaffari in issue https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/620 .

Fix for sprintf when compiling with nano.specs option set.

---

STM32F1/cores/maple/libmaple/i2c.c

I'm not 100% certain that this fixes #799 or not (since my lab is still in shambles) but these are definitely two cases missing a necessary STOP condition on a bus master.
Please test with your setup for #799.  If it doesn't fix it, you can reopen the issue and I will continue my probing to try and resolve it.

Fix STOP condition on I2C Master for Bus Error and Timeout

---

STM32F1/cores/maple/wirish.h

Here is the requested PR.
Thanks
Armin

Fixing error: 'utoa' was not declared in this scope - see #884
